# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: postgresql
  username: "postgres"
  password: "Karthik@123"
  database: "fave"
  encoding: utf8
  host: "localhost"
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  encoding: unicode
  database: "fave"
  username: "postgres"
  password: "Karthik@123"
  host: "localhost"
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: "fave"
  username: "postgres"
  password: "Karthik@123"
  host: "localhost"
  port: 5432
